
.PHONY: docs_clean

# Generisi HTML dokumentaciju	
doc : doc_mem

doc_clean : doc_mem_clean doc_evt_clean
	
doc_mem_clean :
	@echo 'Cleaning up documentation'
	rm -rf ../doc/out/mem/*
	@echo 'Finished Cleaning up documentation'
	@echo ' '

doc_mem : doc_mem_clean
	@echo 'Building Memory Management documentation'
	@echo 'Invoking: Doxygen doxyfile-mem'
	cd ../doc && $(DOXYGEN) doxyfile-mem
	@echo 'Finished building documentation'
	@echo ' '

doc_evt_clean :
	@echo 'Cleaning up documentation'
	rm -rf ../doc/out/evt/*
	@echo 'Finished Cleaning up documentation'
	@echo ' '
