
.PHONY: docs_clean

# Generisi HTML dokumentaciju	
docs : docs_clean
	@echo 'Building HTML documentation'
	@echo 'Invoking: Doxygen'
	cd .. && $(DOXYGEN) Doxyfile
	@echo 'Finished building HTML documentation'
	@echo ' '
	
docs_clean :
	@echo 'Cleaning up documentation'
	rm -rf ../doc/html/*
	rm -rf ../doc/latex/*
	rm -rf ../doc/man/*
	@echo 'Finished Cleaning up documentation'
	@echo ' '